### ISSUE TITLE
Asimilation of  rcb to ramda-adjunct

### ISSUE THREAD

**Issue by char0n** [enten/rcb#1]
Hi,

Firstly I would like to say nice work on the code. I am author of [ramda-adjunct](https://github.com/char0n/ramda-adjunct) and I would like to absorb your code into ramda-adjunct codebase. it is shame that this code sits here, without tests and documentation. Also the code contains o lot of bugs that can be easily fixed and make it production ready.

What I am proposing are these steps that I will execute in this order:

1.) absorb your codebase
2.) document it
3.) cover it with 100% test coverage and make it production ready

I am asking you for a permission to put a note into ramda-adjunct README.md that your library got absorbed by ramda-adjunct and that you are original author of some of the code in it. It would also by nice if you put a link into rcb readme about the absorbtion. It would also be great if you continue your work on pull-request basis on ramda-adjuct. 

What do you think ?

**Comment by enten** [comment]
Hi! Firstly: thank you for you work.

Rcb is an experimentation with ramda. I never had the time to create a first production ready version of it.

I will be happy if that little work can be reused. So I'm totally agree with you.

> It would also by nice if you put a link into rcb readme about the absorbtion.

Can you make a PR with the adjustments that you want?

**Comment by char0n** [comment]
Ok, than it's a deal. I'll create the PR when everything is ready.

**Comment by char0n** [comment]
@enten finished my work on type functions. https://char0n.github.io/ramda-adjunct/0.7.0/

My next step is to include current ramda cookbook into codebase . Today I will issue a pull request for your repo about ramda-adjnuct and add note to ramda-adjunct README about your part in it.
